import {createElement as h} from "react";
import {Toolbar, ToolbarButton, ToolbarGroup, ToolbarSeparator, IconButton,
  Card, SearchField, Button} from "../../../../packages/react/dist/index.js";

const row = {display: "flex", flexWrap: "wrap", alignItems: "center", gap: "var(--space-2)"};

export default [
  {
    variant: "Horizontal",
    name: "Formatting bar",
    description: "Style and align in named groups, one tab stop for the whole bar.",
    uses: ["Toolbar", "ToolbarGroup", "ToolbarButton", "ToolbarSeparator"],
    code: [
      '<Toolbar label="Formatting">',
      '  <ToolbarGroup label="Style">',
      '    <ToolbarButton pressed>Bold</ToolbarButton>',
      '    <ToolbarButton>Italic</ToolbarButton>',
      '  </ToolbarGroup>',
      '  <ToolbarSeparator />',
      '  <ToolbarGroup label="Align">',
      '    <ToolbarButton>Left</ToolbarButton>',
      '    <ToolbarButton>Center</ToolbarButton>',
      '  </ToolbarGroup>',
      '</Toolbar>',
    ].join("\n"),
    render: () => h(Toolbar, {label: "Formatting"},
      h(ToolbarGroup, {label: "Style"},
        h(ToolbarButton, {pressed: true}, "Bold"), h(ToolbarButton, null, "Italic")),
      h(ToolbarSeparator),
      h(ToolbarGroup, {label: "Align"},
        h(ToolbarButton, null, "Left"), h(ToolbarButton, null, "Center"))),
  },
  {
    variant: "Horizontal",
    name: "Table header bar",
    description: "Search on one side, actions on the other — the bar that heads a collection.",
    uses: ["Card", "SearchField", "Toolbar", "IconButton"],
    code: [
      '<div className="cluster" style={{justifyContent: "space-between"}}>',
      '  <SearchField placeholder="Filter rows…" />',
      '  <Toolbar label="Table actions">',
      '    <IconButton icon="filter" label="Filter" />',
      '    <IconButton icon="download" label="Export" />',
      '  </Toolbar>',
      '</div>',
    ].join("\n"),
    render: () => h("div", {style: {...row, justifyContent: "space-between", width: "min(560px,100%)"}},
      h("div", {style: {flex: 1, minWidth: "180px"}}, h(SearchField, {placeholder: "Filter rows…"})),
      h(Toolbar, {label: "Table actions"},
        h(IconButton, {icon: "filter", label: "Filter"}),
        h(IconButton, {icon: "download", label: "Export"}))),
  },
  {
    variant: "Vertical",
    name: "Side rail",
    description: "A column of tools beside a canvas: up and down navigate, the separator turns with the axis.",
    uses: ["Toolbar", "IconButton", "ToolbarSeparator"],
    code: [
      '<Toolbar orientation="vertical" label="Tools">',
      '  <IconButton icon="edit" label="Draw" />',
      '  <IconButton icon="image" label="Place image" />',
      '  <ToolbarSeparator />',
      '  <IconButton icon="trash-can" label="Erase" variant="danger-ghost" />',
      '</Toolbar>',
    ].join("\n"),
    render: () => h(Toolbar, {orientation: "vertical", label: "Tools"},
      h(IconButton, {icon: "edit", label: "Draw"}),
      h(IconButton, {icon: "image", label: "Place image"}),
      h(ToolbarSeparator),
      h(IconButton, {icon: "trash-can", label: "Erase", variant: "danger-ghost"})),
  },
  {
    variant: "Horizontal",
    name: "Undo and redo",
    description: "History with the unavailable step kept in place, so the arrows never renumber the set.",
    uses: ["Toolbar", "ToolbarButton"],
    code: [
      '<Toolbar label="History">',
      '  <ToolbarButton leadingIcon="undo" disabled>Undo</ToolbarButton>',
      '  <ToolbarButton leadingIcon="redo">Redo</ToolbarButton>',
      '</Toolbar>',
    ].join("\n"),
    render: () => h(Toolbar, {label: "History"},
      h(ToolbarButton, {leadingIcon: "undo", disabled: true}, "Undo"),
      h(ToolbarButton, {leadingIcon: "redo"}, "Redo")),
  },
];
